import torch
import torch.nn.functional as F
from transformer_lens import HookedTransformer
import matplotlib.pyplot as plt
import numpy as np

# 1. Setup Environment
print("Loading Shadow AI (GPT-2 Small)...")
model = HookedTransformer.from_pretrained("gpt2-small")

def analyze_existing_response(prompt, full_response):
    """
    This function acts as the "Shadow AI". It takes a prompt and a response 
    already generated by another AI (like Gemini) and runs it through the local 
    transformer to map the internal math and check for hallucinations.
    """
    # Combine prompt and response (Add a space so tokens don't merge weirdly)
    combined_text = prompt + " " + full_response
    
    # Tokenize
    tokens = model.to_tokens(combined_text)
    str_tokens = model.to_str_tokens(combined_text)
    
    # Calculate exactly where the prompt ends and the response begins
    prompt_length = len(model.to_str_tokens(prompt))
    
    print(f"\n[Shadow AI] Running deep analysis on {len(str_tokens)} total tokens...")
    
    # Run the math on the ALREADY WRITTEN text! (Batch Processing)
    # This is incredibly fast because it's a single forward pass, not a loop!
    logits, cache = model.run_with_cache(tokens)
    
    results = []
    print(f"\n--- Shadow AI Analysis Report ---")
    print(f"Prompt: '{prompt}'")
    print("-" * 60)
    
    # Analyze only the tokens that make up the response
    for i in range(prompt_length, len(str_tokens)):
        token_str = str_tokens[i]
        
        # A. MEASURE ENTROPY (Confusion)
        # The prediction for token `i` was made using the context up to `i-1`
        prev_logit = logits[0, i-1, :]
        probs = F.softmax(prev_logit, dim=-1)
        entropy = -torch.sum(probs * torch.log(probs + 1e-9)).item()
        
        # B. MEASURE PROMPT INFLUENCE (Aggregated Anchor Strategy)
        # How much did token `i` look back at the ENTIRE prompt?
        layer_range = range(5, 9) # Middle layers focus on conceptual linking
        total_prompt_attn = 0
        
        for l in layer_range:
            # pattern shape: [batch, head, query_pos, key_pos]
            # sum attention across all prompt tokens (0 to prompt_length), average across all 12 heads
            prompt_block_attn = cache["pattern", l][0, :, i, 0:prompt_length].sum(dim=-1).mean().item()
            total_prompt_attn += prompt_block_attn
            
        avg_influence = total_prompt_attn / len(layer_range)
        
        # C. CLASSIFY STATE
        status = "TRUSTED"
        if avg_influence < 0.05: 
            status = "DRIFTING"
        if entropy > 4.5: 
            status = "GUESSING"
        if avg_influence < 0.05 and entropy > 5.0: 
            status = "HALLUCINATION!"
            
        results.append({
            "token": token_str,
            "influence": avg_influence,
            "entropy": entropy,
            "status": status
        })
        
        print(f"[{status:14}] Word: {token_str:15} | Prompt Influence: {avg_influence:.4f} | Confusion: {entropy:.2f}")

    return results, str_tokens[prompt_length:]

def deep_qa_audit(prompt, response):
    # This detects "Reasoning Hallucinations" 
    # where the model starts logical, but loses it halfway through.
    
    results, response_tokens = analyze_existing_response(prompt, response)
    
    print("\n--- Deep Q&A Audit (Drift Velocity) ---")
    # Calculate the "Drift Velocity"
    # How fast is the Influence dropping?
    influences = [r['influence'] for r in results]
    drift_velocity = np.diff(influences)
    
    for i, dv in enumerate(drift_velocity):
        if dv < -0.01: # Sudden loss of context
            print(f"ALERT: Logic snap detected! Sudden drop in prompt influence at token '{response_tokens[i+1]}'")
            
    return results, response_tokens

# --- STRESS TEST THE SHADOW AI ---
# We will feed it a prompt, and a "fake" Gemini response that contains a blatant lie at the end.
user_prompt = "What is the capital of Japan?"
gemini_response = "The capital of Japan is Tokyo. It is known for its tall skyscrapers and the Eiffel Tower."

report, response_tokens = deep_qa_audit(user_prompt, gemini_response)


# --- VISUALIZATION ---
influences = [r['influence'] for r in report]
entropies = [r['entropy'] for r in report]

fig, ax1 = plt.subplots(figsize=(14, 6))

ax1.set_xlabel('Generated Tokens (from External AI)')
ax1.set_ylabel('Prompt Influence (Attention)', color='blue')
ax1.plot(response_tokens, influences, color='blue', marker='o', label='Influence (Higher = Staying on Topic)')
ax1.tick_params(axis='y', labelcolor='blue')

ax2 = ax1.twinx()
ax2.set_ylabel('Model Confusion (Entropy)', color='red')
ax2.plot(response_tokens, entropies, color='red', marker='x', linestyle='--', label='Confusion (Higher = Guessing)')
ax2.tick_params(axis='y', labelcolor='red')

plt.title(f"Shadow AI Fact-Check: '{user_prompt}'")
plt.xticks(rotation=45)
fig.tight_layout()
plt.savefig('shadow_analysis.png')
print("\nShadow Analysis Chart saved to shadow_analysis.png")

# --- PHASE 3: LOGIT DIVERGENCE & CONFLICT ANALYZERS ---

def analyze_logit_divergence(prompt, response):
    combined_text = prompt + " " + response
    tokens = model.to_tokens(combined_text)
    str_tokens = model.to_str_tokens(combined_text)
    prompt_len = len(model.to_str_tokens(prompt))
    
    # Run the forward pass
    logits, _ = model.run_with_cache(tokens)
    
    print(f"\n--- Logit Divergence Analysis ---")
    print(f"{'Word':<15} | {'Chosen':<10} | {'Top Alternatives (Probability)':<40}")
    print("-" * 75)

    for i in range(prompt_len, len(str_tokens)):
        current_logits = logits[0, i-1, :]
        probs = F.softmax(current_logits, dim=-1)
        
        # Get Top 3 candidates
        top_values, top_indices = torch.topk(probs, 3)
        chosen_token = str_tokens[i]
        
        # Format the top 3 for display
        alts = []
        for val, idx in zip(top_values, top_indices):
            token_name = model.to_string(idx)
            alts.append(f"'{token_name}' ({val:.1%})")
        
        # Hallucination Check: High Divergence
        # If the gap between #1 and #2 is small, the model is 'Diverging'
        gap = top_values[0] - top_values[1]
        alert = "[!]" if gap < 0.1 else "   " # Alert if gap is less than 10%
        
        print(f"{alert} {chosen_token:<13} | {chosen_token.strip():<10} | {' vs '.join(alts)}")


def analyze_conflict(prompt, external_response):
    combined_text = prompt + " " + external_response
    tokens = model.to_tokens(combined_text)
    str_tokens = model.to_str_tokens(combined_text)
    prompt_len = len(model.to_str_tokens(prompt))
    
    # Forward pass to get Shadow AI's predictions
    logits, _ = model.run_with_cache(tokens)
    
    print(f"\n--- Model Conflict Report ---")
    print(f"{'Status':<18} | {'Gemini Said':<12} | {'Shadow AI Predicted instead...'}")
    print("-" * 70)

    for i in range(prompt_len, len(str_tokens)):
        actual_token_id = tokens[0, i]
        actual_token_str = str_tokens[i]
        
        shadow_probs = F.softmax(logits[0, i-1, :], dim=-1)
        
        # Conflict Score: Probability the Shadow AI gave to Gemini's word
        prob_of_actual = shadow_probs[actual_token_id].item()
        conflict_score = 1 - prob_of_actual
        
        # Get the Shadow AI's preferred word
        top_shadow_id = shadow_probs.argmax().item()
        top_shadow_str = model.to_string(top_shadow_id)
        
        # Flagging Logic
        status = "[OK]"
        if conflict_score > 0.95: status = "[HIGH CONFLICT]"
        elif conflict_score > 0.80: status = "[WARN]"

        print(f"{status:16} | {actual_token_str:12} | Shadow wanted: '{top_shadow_str.strip()}' ({shadow_probs[top_shadow_id]:.1%})")

# Test it with the Japan/Eiffel Tower hallucination
fake_response_2 = "The capital of Japan is Tokyo. It is known for the Eiffel Tower."

analyze_logit_divergence(user_prompt, fake_response_2)
analyze_conflict(user_prompt, fake_response_2)
